### ISSUE TITLE
How to connect Debezium, kafka to mysql servers 

### ISSUE THREAD

**Issue by phucle2411** [debezium/debezium-examples#39]
I have read all tutorials on the official page of debezium, but I can't find out the way how to connect Debezium and kafka to mysql server (I have some mysql servers have been running on hosts - not docker). I have already run docker containers for zookeeper and kafka like the tutorial shows.
Please let me know the way connect to existing mysql servers running on hosts

**Comment by jpechane** [comment]
@phucle2411 Hi, you should just provide the correct IP and credentials of your db server in the registration request - the one `POST`ed to Connect API

**Comment by gunnarmorling** [comment]
Hi, please follow exactly the steps from the tutorial. If things still don't work, please send a mail to [our list](https://groups.google.com/forum/#!forum/debezium) with the exact errors/exceptions you see, otherwise it's not really possible to help. Going to close this issue, as this tracker here is just for issues with examples themselves. Cheers!
